name: "Posterr"
description: "Posterr integration for Home Assistant"
url: https://github.com/petersem/posterr
webui: http://[HOST]:[PORT:3000]
version: "0.12"
slug: "posterr_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3000/tcp: 3000
map:
  - share:rw
volumes:      
  - /share/posterr/configs:/usr/src/app/config # Make sure your local config directory exists
  - /share/posterr/custom:/usr/src/app/public/custom # Make sure your local config directory exists
environment:
      TZ: Europe/Lisbon
