---
channel: stable
addons:
  homepage:
    repository: ha-addons/homepage
    target: homepage
  posterr:
    repository: ha-addons/posterr
    target: posterr
  rdtclient:
    repository: ha-addons/rdtclient
    target: rdtclient
