name: "Homepage"
description: "Homepage integration for Home Assistant"
url: https://gethomepage.dev/
webui: http://[HOST]:[PORT:3000]
version: "0.36"
slug: "homepage_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3000/tcp: 3000
map:
  - share:rw
volumes:      
  - /share/homepage/configs:/app/config # Make sure your local config directory exists
schema:
  HOMEPAGE_ALLOWED_HOSTS: "str"
environment:
      TZ: Europe/Lisbon
      HOMEPAGE_ALLOWED_HOSTS: /app/config/host.txt
