name: "Cloudflare DDNS"
version: "2.2.0"
slug: "cloudflare_ddns"
description: "Atualiza automaticamente registos DNS da Cloudflare com o IP público."
url: https://github.com/timothymiller/cloudflare-ddns
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
image: "timothymiller/cloudflare-ddns"
options:
  cloudflare_api_token: ""
  ip4_domains: ""
  proxied: ""
  update_cron: "@every 5m"
  update_on_start: true
  ip6_provider: "none"
  ttl: 1
  delete_on_stop: false
  delete_on_failure: false
  emoji: true
schema:
  cloudflare_api_token: password
  ip4_domains: str
  proxied: str
  update_cron: str
  update_on_start: bool
  ip6_provider: str
  ttl: int
  delete_on_stop: bool
  delete_on_failure: bool
  emoji: bool
