name: "Leitura da Agua"
description: "Leitura da agua CMSC"
url: https://github.com/rogerfar/rdt-client/blob/master/README.md
webui: http://[HOST]:[PORT:4444]
version: "0.04"
slug: "leitura_agua_bot"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4444/tcp: 4444
volumes:
  - /share/leitura_agua/app:/app
working_dir: /app
command: ["python3", "enviar_leitura.py"]
