name: "Leitura da Agua"
description: "Leitura da agua CMSC"
url: https://github.com/rogerfar/rdt-client/blob/master/README.md
webui: http://[HOST]:[PORT:7900]
version: "0.01"
slug: "leitura_agua_bot"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  7900/tcp: 7900
map:
  - share:rw
volumes:      
  /share/leitura_agua/app:/app # Make sure your local config directory exists
environment:
      TZ: Europe/Lisbon
command: ["python3", "enviar_leitura.py"]
