name: "wizarr"
description: "wizarr integration for Home Assistant"
version: "0.01"
slug: "wizarr_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3000/tcp: 3000
map:
  - share:rw
volumes:      
  - /share/homepage/configs:/app/config # Make sure your local config directory exists
