name: "wizarr"
description: "wizarr integration for Home Assistant"
url: https://github.com/dmtg/ha-addons/blob/main/wizarr/README.md
webui: http://[HOST]:[PORT:5690]
version: "0.03"
slug: "wizarr_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5690/tcp: 5690
map:
  - share:rw
volumes:      
  /share/wizarr/configs:/data/database # Make sure your local config directory exists
