name: "wizarr"
description: "wizarr integration for Home Assistant"
version: "0.02"
slug: "wizarr_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3000/tcp: 3000
map:
  - share:rw
volumes:      
  /share/wizarr/configs:/data/database # Make sure your local config directory exists
