name: "RDTCLIENT"
description: "Real-Debrid Client Proxy integration for Home Assistant"
version: "0.07"
slug: "rdtclient_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  6500/tcp: 6500
map:
  - share:rw
volumes:      
  - /share/rtclient/downloads:/data/downloads # Make sure your local config directory exists
 environment:
  - TZ=Europe/Lisbon    
  - PUID=3
  - PGID=3
