name: "Maintainerr"
description: "Maintainerr integration for Home Assistant"
url: "https://github.com/Maintainerr/Maintainerr"
webui: "http://[HOST]:[PORT:6246]"
version: "3.3.0.24"
slug: "maintainerr_addon"
startup: application
boot: auto
init: false

arch:
  - aarch64
  - amd64

ports:
  6246/tcp: 6246

ports_description:
  6246/tcp: "Maintainerr Web UI"
