name: "Mantainerr"
description: "Maintainerr integration for Home Assistant"
url: https://github.com/dmtg/ha-addons/blob/main/mantainerr/README.md
webui: http://[HOST]:[PORT:6246]
version: "3.3.0.6"
slug: "maintainerr_addon"
init: true
host_network: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  6246/tcp: 6246

map:
  - addon_config:rw
environment:
  TZ: Europe/Lisbon

privileged:
  - SYS_ADMIN

options:
  TZ: Europe/Lisbon
  LOG_LEVEL: info

schema:
  TZ: str
  LOG_LEVEL: list(trace|debug|info|warning|error)
