name: "Maintainerr"
version: "3.3.0.4"
slug: "maintainerr"
description: "Rule-based media cleanup for Plex, Jellyfin and Emby"
url: "https://github.com/Maintainerr/Maintainerr"
startup: application
boot: auto
init: false

arch:
  - amd64
  - aarch64

webui: "http://[HOST]:[PORT:6246]"

ports:
  6246/tcp: 6246

ports_description:
  6246/tcp: "Maintainerr Web UI"

map:
  - type: share
    read_only: false
    path: /opt/data
user: '1000:1000'
environment:
  TZ: "Europe/Lisbon"
  LOG_LEVEL: info
  
schema:
  TZ: str
  LOG_LEVEL: list(trace|debug|info|warning|error)
